### ISSUE TITLE
error compiling icedtea-web

### ISSUE THREAD

**Issue by latot** [gentoo/java-overlay#26]
Hi, here come errors compiling it here the log:

https://gist.github.com/latot/425f31c68b9a227aee87

emerge --info
[emerge.txt](https://github.com/gentoo/java-overlay/files/31985/emerge.txt)
Thx.

**Comment by chewi** [comment]
I've not tried it with icedtea-8 yet so that may be the cause. It's long overdue a version bump and other fixes but it hasn't bubbled to the top of my list yet.

**Comment by latot** [comment]
mm, i'll try with icedtea:7 and this happend with the doc flag
Thx.

**Comment by chewi** [comment]
Ah thanks for the doc hint, I missed that. This will be because Java 8's javadoc is much stricter and requires you to pass `-Xdoclint:none` to avoid this problem. I'll add this to the pile then!

**Comment by latot** [comment]
Thx!

**Comment by chewi** [comment]
I dealt with this in 1.6.1.
