### ISSUE TITLE
Error compiling IcedTea 8 without zero flag

### ISSUE THREAD

**Issue by latot** [gentoo/java-overlay#27]
Hi, i get some errors compiling dev-java/icedtea-3.0.0_pre06 with "-zero"

Thx. Cya.

[icedtea-nozero.txt](https://github.com/gentoo/java-overlay/files/40881/icedtea-nozero.txt)
[emerge-info.txt](https://github.com/gentoo/java-overlay/files/40883/emerge-info.txt)

**Comment by chewi** [comment]
While Java team actively encourages pull requests via GitHub, we would prefer bug reports on [Bugzilla](https://bugs.gentoo.org) where they can be tracked more easily. I cannot help with this at present as I am not yet familiar with icedtea-3 but I will give @gnu-andrew a heads up.

**Comment by latot** [comment]
Okis, thx. i'll post the next issues via bugzila.

Its necesary repost this on bugzilla? Thx.

**Comment by chewi** [comment]
Nah, it's cool.

**Comment by pvgoran** [comment]
Forgive me for hijacking the issue, but how do you compile icedtea-3.0.0_pre06 at all? All I ever got was emerge complaining "Filesize does not match recorded size" about the source file, and this is right after I do layman --sync-all. (This goes for the -pre versions in slot 7 as well.)

**Comment by chewi** [comment]
@gnu-andrew has explained in [bug #568572](https://bugs.gentoo.org/show_bug.cgi?id=568572) that he hasn't got around to bumping the ebuild yet. Please note that icedtea ebuilds in java-overlay are not maintained by Gentoo developers. I am only responsible for the ones in the main tree.

**Comment by pvgoran** [comment]
Thanks for the reference. I was already having an impression that these -pre ebuilds don't have their metadata updated vs. icedtea.classpath.org source archives, and the build log from the OP suggested that the sources are taken from Mercurial rather than extracted from the archives.

**Comment by gnu-andrew** [comment]
----- Original Message -----
> Forgive me for hijacking the issue, but how do you compile
> icedtea-3.0.0_pre06 at all? All I ever got was emerge complaining "Filesize
> does not match recorded size" about the source file, and this is right after
> I do layman --sync-all. (This goes for the -pre versions in slot 7 as well.)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gentoo/java-overlay/issues/27#issuecomment-166911918

pre07 is available now.
-- 
Andrew :)

Senior Free Java Software Engineer
Red Hat, Inc. (http://www.redhat.com)

PGP Key: ed25519/35964222 (hkp://keys.gnupg.net)
Fingerprint = 5132 579D D154 0ED2 3E04  C5A0 CFDA 0F9B 3596 4222

PGP Key: rsa4096/248BDC07 (hkp://keys.gnupg.net)
Fingerprint = EC5A 1F5E C0AD 1D15 8F1F  8F91 3B96 A578 248B DC07

**Comment by latot** [comment]
reopen it please D:
https://bugs.gentoo.org/show_bug.cgi?id=569760
