### ISSUE TITLE
Testing out =dev-java/icedtea-3.0.0_pre09 - Upstream new release bundle - today??

### ISSUE THREAD

**Issue by bobwya** [gentoo/java-overlay#30]
Hi,
I was trying to build the source-based version of icedtea... But I'm getting a whole lot of manifest errors from all the files in the bundle:
```
!!! Fetched file: icedtea-3.0-openjdk-a358b13af298.tar.xz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      330172
!!! Expected: 329880
Refetching... File renamed to '/usr/portage/distfiles/icedtea-3.0-openjdk-a358b13af298.tar.xz._checksum_failure_.il12ehzf'
```

Then of course later on the file **SHA256SUM** 's fail - if I forcibly try to manually update the manifest files...

It appears the directory:
[http://icedtea.wildebeest.org/download/drops/icedtea8/3.0.0/](http://icedtea.wildebeest.org/download/drops/icedtea8/3.0.0/)
has a timestamp of 2016-03-30 (i.e. today!!)

**Comment by chewi** [comment]
There was an update to pre10 today but it turns out gnu_andrew forgot to push. Thanks for the heads up!
