### ISSUE TITLE
icedtea:8 infinality support

### ISSUE THREAD

**Issue by rindeal** [gentoo/java-overlay#31]
Is infinality support planned for icedtea:8?

**Comment by chewi** [comment]
Were you the guy asking about icedtea:8 font rendering on IRC the other day? I hadn't actually noticed that Infinality is missing from that ebuild. @gnu-andrew?

**Comment by rindeal** [comment]
> Were you the guy asking about icedtea:8 font rendering on IRC the other day?
No, I'm not aware of doing that.

**Comment by chewi** [comment]
Upstream is adding it to the next release.

**Comment by strelec** [comment]
configure: error: Infinality support requires infinality support in FreeType.

Even though the freetype package has the USE="infinality" and is properly built with this flag.

**Comment by chewi** [comment]
@strelec, see [Gentoo bug #590068](https://bugs.gentoo.org/show_bug.cgi?id=590068).
