### ISSUE TITLE
net-mail/davmail-3.9.1-r1 depends on masked java-virtuals/javamail:0

### ISSUE THREAD

**Issue by adlerweb** [gentoo/java-overlay#42]
net-mail/davmail-3.9.1-r1 depends on java-virtuals/javamail:0 which is masked and marked for removal [1]. It is recommended to replace it with dev-java/oracle-javamail instead. Updating CDEPEND and EANT_GENTOO_CLASSPATH seems to compile fine.

Since this ebuild is outdated [2] and up-to-date alternatives are available [3] it should also be checked if keeping this package in the overlay is a good idea. Updating looks to require some work since this ebuild patches the software to use system libraries instead of the bundled ones and current versions depend on several new libraries (wstx, etc).

[1] https://bugs.gentoo.org/show_bug.cgi?id=553186
[2] https://sourceforge.net/projects/davmail/files/davmail/4.8.0/
[3] https://gitweb.gentoo.org/user/seden.git/tree/net-mail/davmail-bin/

**Comment by chewi** [comment]
Thanks for bringing this up, I rarely check java-overlay these days. I could fix it easily enough but it may as well go now. We're looking towards a new approach to packaging so maybe it could come back later.

**Comment by chewi** [comment]
Done.
